CREATE TABLE shop.refresh_token
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    token    VARCHAR(255) NOT NULL,
    exp_date TIMESTAMP NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    mod_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    CONSTRAINT FK_REFRESH_TOKEN_USER_ID FOREIGN KEY (user_id) REFERENCES shop.users (id)
);
