CREATE TABLE shop.product_details
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id  BIGINT NULL,
    description VARCHAR(2000) NULL,
    content     VARCHAR(10000) NULL,
    reg_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    mod_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    CONSTRAINT FK_PRODUCT_DETAILS_PRODUCT_ID FOREIGN KEY (product_id) REFERENCES shop.products (id)
);
